FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_WHATSAPP_NUMBER
ARG NEXT_PUBLIC_WHATSAPP_NUMBER_DISPLAY
ARG NEXT_PUBLIC_UPI_VPA
ARG NEXT_PUBLIC_UPI_NAME
ARG NEXT_PUBLIC_CALCOM_LINK
ENV NEXT_PUBLIC_WHATSAPP_NUMBER=$NEXT_PUBLIC_WHATSAPP_NUMBER
ENV NEXT_PUBLIC_WHATSAPP_NUMBER_DISPLAY=$NEXT_PUBLIC_WHATSAPP_NUMBER_DISPLAY
ENV NEXT_PUBLIC_UPI_VPA=$NEXT_PUBLIC_UPI_VPA
ENV NEXT_PUBLIC_UPI_NAME=$NEXT_PUBLIC_UPI_NAME
ENV NEXT_PUBLIC_CALCOM_LINK=$NEXT_PUBLIC_CALCOM_LINK

RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000
ENV PORT=3000
CMD ["node", "server.js"]
